name: Notify Telegram on Push

on:
  push:
    branches:
      - main  # Можешь указать другие ветки, если нужно

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Telegram Notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id="-1002581290046" \
            -d text="📌 Новый push в репозиторий: ${{ github.repository }}\n👤 Автор: ${{ github.actor }}\n🔗 Коммит: ${{ github.event.head_commit.url }}\n📝 Сообщение: ${{ github.event.head_commit.message }}"
